# Generated by Django 5.0.6 on 2024-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('input', models.CharField(max_length=100)),
                ('lat1', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lon1', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat2', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lon2', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat3', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lon3', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
