# Generated by Django 5.0.6 on 2024-06-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='input',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='react',
            name='lat1',
        ),
        migrations.RemoveField(
            model_name='react',
            name='lat2',
        ),
        migrations.RemoveField(
            model_name='react',
            name='lat3',
        ),
        migrations.RemoveField(
            model_name='react',
            name='lon1',
        ),
        migrations.RemoveField(
            model_name='react',
            name='lon2',
        ),
        migrations.RemoveField(
            model_name='react',
            name='lon3',
        ),
        migrations.RemoveField(
            model_name='react',
            name='type',
        ),
    ]
