# Generated by Django 5.0.6 on 2024-09-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lat2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lat3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('query_date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
