# Generated by Django 5.0.6 on 2024-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat3',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lon3',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
