# Generated by Django 5.0.6 on 2024-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('query_date', models.DateTimeField(auto_now_add=True)),
                ('lat1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lat2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lat3', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('lon3', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
