# Generated by Django 5.0.6 on 2024-09-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iplocation',
            old_name='ip_address',
            new_name='input_data',
        ),
    ]
